# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='person',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Por'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/images', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
    ]
