# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20160825_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='person',
            field=models.CharField(blank=True, max_length=20, verbose_name='Por'),
        ),
    ]
