# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_auto_20160825_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='value',
            field=models.CharField(blank=True, max_length=15, verbose_name='Valor'),
        ),
    ]
