# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_auto_20161006_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='value',
            field=models.CharField(blank=True, choices=[('grátis', 'Gratuito'), ('12', 'R$12'), ('22', 'R$22'), ('31', 'R$31'), ('42', 'R$42'), ('63', 'R$63'), ('74', 'R$74'), ('97', 'R$97'), ('112', 'R$112'), ('197', 'R$197'), ('227', 'R$227'), ('397', 'R$397'), ('437', 'R$437'), ('537', 'R$537'), ('737', 'R$737'), ('937', 'R$937'), ('1197', 'R$1197'), ('1997', 'R$1997'), ('2997', 'R$2997'), ('3997', 'R$3997'), ('4997', 'R$4997')], default='31', max_length=15, null=True, verbose_name='Preço'),
        ),
    ]
