# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_curso_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-created_at'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
