# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 02:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_auto_20161006_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
