# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_auto_20161006_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='value',
            field=models.CharField(blank=True, choices=[('Grátis', 'Grátis'), ('R$12', 'R$12'), ('R$22', 'R$22'), ('R$31', 'R$31'), ('R$42', 'R$42'), ('R$63', 'R$63'), ('R$74', 'R$74'), ('R$97', 'R$97'), ('R$112', 'R$112'), ('R$197', 'R$197'), ('R$227', 'R$227'), ('R$397', 'R$397'), ('R$437', 'R$437'), ('R$537', 'R$537'), ('R$737', 'R$737'), ('R$937', 'R$937'), ('R$1197', 'R$1197'), ('R$1997', 'R$1997'), ('R$2997', 'R$2997'), ('R$3997', 'R$3997'), ('R$4997', 'R$4997')], default='31', max_length=15, null=True, verbose_name='Preço'),
        ),
    ]
