# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_auto_20161013_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/materials', verbose_name='Adicionar arquivo'),
        ),
    ]
