# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_auto_20160831_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/images', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='cursos.Curso', verbose_name='Curso'),
        ),
    ]
