# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_auto_20160831_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='image',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='cursos.Curso', verbose_name='Curso'),
        ),
    ]
